services:
  backend:
    build:
      context: ./backend/build
    volumes:
      - .:/workspace
    depends_on:
      - db
    command: sleep infinity
  frontend:
    build:
      context: ./frontend/build
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    command: sleep infinity
    # depends_on:
    #   - backend
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/data:/var/lib/postgresql/data
  #redis
